services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/opportunities"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}

  dashboard:
    build:
      context: ./dashboard/client
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

  watchdog:
    image: node:20-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: ["node", "utils/crash-watcher.js"]
    depends_on:
      backend:
        condition: service_healthy
