services:
  - type: web
    name: flashbot-backend
    runtime: node
    plan: free
    buildCommand: yarn install
    startCommand: yarn start
    envVars:
      - key: PORT
        value: 5000
      - key: API_SECRET
        value: ton_token_securisé
      - key: NODE_ENV
        value: production
